dataset_root: ''
camera_shape: [84,84]
obs_mode: "rgbd"
control_mode: "pd_ee_delta_pose"
camera_keys: [base_camera,hand_camera]
state_keys: [qpos, goal_pos]
render_mode: "cameras"
num_demos: 1000
num_train_frames: 30250
low_dim_obs_shape: 12
